name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    # es recomendable poner una versión en específico. Si no, al salir una nueva versión, se puede romper todo
    runs-on: ubuntu-22.04
    steps:
      # el nombre de los pasos es opcional
      - name: Echo the message
        run: |
          echo "Hola midu!"
      - name: Dime la fecha
        run: date
      - run: ls -l