name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    # las acciones se pueden componer de otras acciones
    steps:
      # esta acción sirve para traernos el código del repo a nuestra máquina de CI
      # nos evita hacer a mano un git clone, pasarle el auth token, config etc
      - uses: actions/checkout@v2
        with:
          # solo se trae el último commit, va más rápido
          fetch-depth: 0
      # ahora lo que queremos es instalar las deps y lintar el código
      # podríamos con nvm instalar node, pero ya hay una acción escrita
      - uses: actions/setup-node@v2
        with:
          # solo se trae el último commit, va más rápido
          node-version: '16' # esto en número o en string?
      - name: Install dependencies
        # run: npm install --no-audit --no-fund --no-optional # para que no instale dependencias opcionales
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          # aunque esto esté en la linea de abajo, se ejecuta antes que los test en el comando de arriba
          start: npm run start-test
          # le decimos que tiene que esperar a que el front se levante antes de ejecutar los tests
          wait-on: 'http://localhost:5000'
      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}